
---
- hosts: localhost
  become: yes

  tasks:
    - name: Build python app1 image
      shell: cd C:/Users/Maathess/Desktop/esgi/4a/S2/DevOps/projet/ansible-samples/app/python_app1 -t pythonapp1:0.1 .
      tags:
        - python
        - build



    - name: Build python app image
      shell: cd C:/Users/Maathess/Desktop/esgi/4a/S2/DevOps/projet/ansible-samples/app/python_app2 -t pythonapp2:0.1 .
      tags:
        - python
        - build


    - name: Run python app container
      shell: docker run -d -p 5001:5000 --name pyapp  pythonapp1:0.1
      tags:
        - run

    - name: Run python app container
        shell: docker run -d -p 5001:5000 --name pyapp  pythonapp2:0.1
        tags:
          - run



    - name: check
      uri:
        url: http://192.168.177.170:8061/fsfs
        method: GET
        status_code: 200
      tags:
        - check

  roles:
  - first_role


