
---
- name: Make sure Web Server is running
  hosts: test
  become: yes
  vars:
    webserver_message: "This is my clever message"

  tasks:
    - name: Start httpd
      service: 
        name: apache2
        state: started
      tags:
        - never

    - name: Create index.html using Jinja2
      template: 
        src: jinja2.j2
        dest: /var/www/html/index.html
